apiVersion: v1
kind: Service
metadata:
  name: app-nginx-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: app-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nginx-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-nginx
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
      - name: nginx
        image: vinaydockersince1980/vinaydockerrepo:webcalc-7
        ports:
        - containerPort: 8080
