apiVersion: v1
kind: Service
metadata:
  name: webcalculator
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: app-webcalculator-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-webcalculator-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-webcalculator
  template:
    metadata:
      labels:
        app: app-webcalculator
    spec:
      containers:
      - name: webcalc-5
        image: webcalc-5
        ports:
        - containerPort: 8080
